spring:
  application:
    name: vehiculos-api
  mongodb:
    database: vehiculos

server:
  port: 8081
  servlet:
    context-path: /api/v1 # Tu API responder√° en localhost:8081/api/v1/vehiculos